[project]
name = "app.demo"
version = "0.1.0"
edition = "latest"
module-root = "src"
output-kind = "binary"
profile = "debug"

[target]
main = "app.demo.Main"
triple = "host"
link = "system"

[paths]
source = ["src"]

[dependencies]
std = "system"